last_name = ('Фамилия: Романов')
name = ('Имя: Роман')
patronymic = ('Отчество: Алексеевич')
age = ('Возраст: 22 года')
gender = ('Пол: Мужской')
place_of_work = ('Место работы: Отдых :)')
place_of_study = ('Место учебы: Lightcode')
course = ('Курс: 1')
the_course = ('Направление: Программирование Python')
have_you_previously_studied_programming = ('Изучали ли программирование раннее?: Раннее программирование не изучал!')
desired_salary = ('Желаемая зарплата: 2000$/3000$ :)')
print(last_name)
print(name)
print(patronymic)
print(age)
print(gender)
print(place_of_work)
print(place_of_study)
print(course)
print(the_course)
print(have_you_previously_studied_programming)
print(desired_salary)