m = ('MacBook Pro')
a = ('13.3')
c = ("Apple M1")
b = ('2020')
oo = ('4 - core processor')
k = ('4 - core graphics processor')
pro = ('SSD 256 GB')
m1 = ('8 GB combined memory')
print(m, a, c, b,)
print(oo)
print(k)
print(pro)
print(m1)


